Feature/person student teacher
patriciachrysy/oop-school-library pull request #1
Opened 2023-11-10 14:16 UTC by patriciachrysy

Hello Dear reviewer,
thanks for taking time to review my code, feedbacks are welcomed. Here is what i did as steps to complete this project:
- Created the Person with constructor, getters, setters and a method for accessibility
-  Created a Student class that inherits Person with another property and that overides it's parent constructor
-  Created a Teacher class that inherits Person with another property and that overides it's parent constructor and the accessibility method
Happy review :-)

2023-11-10 15:34 UTC, Efiamotu-1 requested changes
Hi @patriciachrysy, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-10 15:34 UTC, Efiamotu-1 commented on person.rb
> +  end
- [ ] Your initialize function is missing an id, every new person created should have an id attached to it, see the code snippet below for guidance :+1: 
- code snippet
```ruby
@id = Random.rand(1..1000)
```

2023-11-10 15:34 UTC, Efiamotu-1 commented on person.rb
- [ ] In your readme file, the links you have provided under the `authors` section do not lead to any of your registered accounts with `twitter or linkedIn` please kindly add the appropriate links so that recruiters can easily find you when they look through your readme :+1: :sparkles:

2023-11-10 15:34 UTC, Efiamotu-1 commented on student.rb
> +    super(name, age, parent_permission)
- [ ] In your initialize function coming from the Person class, the first input argument is age not name, please kindly make this important change to your `super` method in your codebase :+1:

2023-11-10 15:34 UTC, Efiamotu-1 commented on teacher.rb
> +    super(name, age, parent_permission)
- [ ] In your initialize function coming from the Person class, the first input argument is age not name, please kindly make this important change to your `super` method in your codebase :+1:

2023-11-11 14:32 UTC, uwadonat approved these changes
## Hi @patriciachrysy ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
- Correct workflow was used ✔️
- Well-organized and clean project ✔️
- No linter error ✔️
- Professional readme file ✔️
![approv](https://github.com/hetrox8/Blog_App/assets/65860678/80ab9621-2395-468f-b148-b3222ba1a2ab)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-11-11 14:32 UTC, merged